/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 07-05-2016 11:07:50
 * Name: gate_monitor_service.h
 * Description:
 *   This file contains definition of an abstract service class.
 ******************************************************************/

#ifndef _ORG_LABCRYPTO_FENCE__SERVICE__ABSTRACT_GATE_MONITOR_SERVICE_H_
#define _ORG_LABCRYPTO_FENCE__SERVICE__ABSTRACT_GATE_MONITOR_SERVICE_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <org/labcrypto/hottentot/runtime/service/service.h>

#include "../message.h"

#include "gate_monitor_service.h"
#include "gate_monitor_service_request_handler.h"
#include "../enums.h"


namespace org {
namespace labcrypto {
namespace fence {
namespace service {
  class AbstractGateMonitorService : public GateMonitorService, public ::org::labcrypto::hottentot::runtime::service::Service {
  public:
    AbstractGateMonitorService() {}
    virtual ~AbstractGateMonitorService() {}
  public:
    inline virtual uint32_t GetServiceId() const {
      return 3779953030;
    }
  protected:
    inline virtual ::org::labcrypto::hottentot::runtime::service::RequestHandler* MakeRequestHandler() {
      return new GateMonitorServiceRequestHandler(this);
    }
  };
} // END OF NAMESPACE service
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org

#endif