/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 07-05-2016 11:11:57
 * Name: fence_service_impl.cc
 * Description:
 *   This file contains empty implementation of sample stub.
 ******************************************************************/
 
#include <org/labcrypto/hottentot/runtime/configuration.h>
#include <org/labcrypto/hottentot/runtime/logger.h>
#include <org/labcrypto/hottentot/runtime/utils.h>

#include "fence_service_impl.h"

#include "../message.h"


namespace org {
namespace labcrypto {
namespace fence {
  void
  FenceServiceImpl::OnInit() {
    // TODO: Called when service is initializing.
  }
  void
  FenceServiceImpl::OnShutdown() {
    // TODO: Called when service is shutting down.
  }
  void
  FenceServiceImpl::Enqueue(
      ::org::labcrypto::fence::Message &message, 
      ::org::labcrypto::hottentot::UInt64 &out, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
  ) {
    if (::org::labcrypto::hottentot::runtime::Configuration::Verbose()) {
      ::org::labcrypto::hottentot::runtime::Logger::GetOut() << 
        "[" << ::org::labcrypto::hottentot::runtime::Utils::GetCurrentUTCTimeString() << "]: " <<
          "FenceServiceImpl::Enqueue() is called." << std::endl;
    }
    // TODO
  }
  void
  FenceServiceImpl::GetStatus(
      ::org::labcrypto::hottentot::UInt64 &id, 
      ::org::labcrypto::hottentot::UInt16 &out, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
  ) {
    if (::org::labcrypto::hottentot::runtime::Configuration::Verbose()) {
      ::org::labcrypto::hottentot::runtime::Logger::GetOut() << 
        "[" << ::org::labcrypto::hottentot::runtime::Utils::GetCurrentUTCTimeString() << "]: " <<
          "FenceServiceImpl::GetStatus() is called." << std::endl;
    }
    // TODO
  }
  void
  FenceServiceImpl::Discard(
      ::org::labcrypto::hottentot::UInt64 &id, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
  ) {
    if (::org::labcrypto::hottentot::runtime::Configuration::Verbose()) {
      ::org::labcrypto::hottentot::runtime::Logger::GetOut() << 
        "[" << ::org::labcrypto::hottentot::runtime::Utils::GetCurrentUTCTimeString() << "]: " <<
          "FenceServiceImpl::Discard() is called." << std::endl;
    }
    // TODO
  }
  void
  FenceServiceImpl::HasMore(
      ::org::labcrypto::hottentot::Utf8String &label, 
      ::org::labcrypto::hottentot::Boolean &out, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
  ) {
    if (::org::labcrypto::hottentot::runtime::Configuration::Verbose()) {
      ::org::labcrypto::hottentot::runtime::Logger::GetOut() << 
        "[" << ::org::labcrypto::hottentot::runtime::Utils::GetCurrentUTCTimeString() << "]: " <<
          "FenceServiceImpl::HasMore() is called." << std::endl;
    }
    // TODO
  }
  void
  FenceServiceImpl::PopNext(
      ::org::labcrypto::hottentot::Utf8String &label, 
      ::org::labcrypto::fence::Message &out, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
  ) {
    if (::org::labcrypto::hottentot::runtime::Configuration::Verbose()) {
      ::org::labcrypto::hottentot::runtime::Logger::GetOut() << 
        "[" << ::org::labcrypto::hottentot::runtime::Utils::GetCurrentUTCTimeString() << "]: " <<
          "FenceServiceImpl::PopNext() is called." << std::endl;
    }
    // TODO
  }
  void
  FenceServiceImpl::Ack(
      ::org::labcrypto::hottentot::UInt64 &id, 
      ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
  ) {
    if (::org::labcrypto::hottentot::runtime::Configuration::Verbose()) {
      ::org::labcrypto::hottentot::runtime::Logger::GetOut() << 
        "[" << ::org::labcrypto::hottentot::runtime::Utils::GetCurrentUTCTimeString() << "]: " <<
          "FenceServiceImpl::Ack() is called." << std::endl;
    }
    // TODO
  }
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org