/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import java.io.IOException;

import org.labcrypto.hottentot.runtime.Service;
import org.labcrypto.hottentot.runtime.ServiceRuntime;


public class SampleServer {
  public static void main(String[] args) throws IOException {
    org.labcrypto.hottentot.runtime.config.Config.setMainArgs(args);
    org.labcrypto.hottentot.runtime.config.Config.setConfigPropertiesFromConfigFile();
    ServiceRuntime serviceRuntime = new ServiceRuntime();
    Service fenceService = new FenceImpl();
    serviceRuntime.register("127.0.0.1",8080, fenceService);
    Service fencemonitorService = new FenceMonitorImpl();
    serviceRuntime.register("127.0.0.1",8080, fencemonitorService);
    Service fencetestService = new FenceTestImpl();
    serviceRuntime.register("127.0.0.1",8080, fencetestService);

    serviceRuntime.start();
  }
}



