/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 07-05-2016 11:11:57
 * Name: message.h
 * Description:
 *   This file contains definition of Message class.
 ***************************************************************/

#ifndef _ORG_LABCRYPTO_FENCE__MESSAGE_H_
#define _ORG_LABCRYPTO_FENCE__MESSAGE_H_

#include <string>

#include <org/labcrypto/hottentot/primitives.h>


#include "enums.h"


namespace org {
namespace labcrypto {
namespace fence {
  class Message : public ::org::labcrypto::hottentot::Serializable {
  public:
    Message() {
    }
    Message(const Message &);
    Message(Message *);
    virtual ~Message() {}
  public:
    inline ::org::labcrypto::hottentot::UInt64 GetId() const {
      return id_;
    }
    inline void SetId(::org::labcrypto::hottentot::UInt64 id) {
      id_ = id;
    }
    inline ::org::labcrypto::hottentot::UInt64 GetRelId() const {
      return relId_;
    }
    inline void SetRelId(::org::labcrypto::hottentot::UInt64 relId) {
      relId_ = relId;
    }
    inline ::org::labcrypto::hottentot::Utf8String GetLabel() const {
      return label_;
    }
    inline void SetLabel(::org::labcrypto::hottentot::Utf8String label) {
      label_ = label;
    }
    inline ::org::labcrypto::hottentot::ByteArray GetContent() const {
      return content_;
    }
    inline void SetContent(::org::labcrypto::hottentot::ByteArray content) {
      content_ = content;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::org::labcrypto::hottentot::UInt64 id_;
    ::org::labcrypto::hottentot::UInt64 relId_;
    ::org::labcrypto::hottentot::Utf8String label_;
    ::org::labcrypto::hottentot::ByteArray content_;
  };
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org

#endif