/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.gate.hotgen;

import ir.ntnaeem.hottentot.runtime.RequestHandler;

public abstract class AbstractGateService implements GateService {	
  public RequestHandler makeRequestHandler() {
    return new GateRequestHandler(this);
  }
  public long getServiceId() {
    return 58024360L;
  }
}
