/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.gate.hotgen;

import ir.ntnaeem.hottentot.runtime.RequestHandler;

public abstract class AbstractGateTestService implements GateTestService {	
  public RequestHandler makeRequestHandler() {
    return new GateTestRequestHandler(this);
  }
  public long getServiceId() {
    return 3053859651L;
  }
}
