/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.gate.hotgen;

import ir.ntnaeem.hottentot.runtime.RequestHandler;

public abstract class AbstractGateMonitorService implements GateMonitorService {	
  public RequestHandler makeRequestHandler() {
    return new GateMonitorRequestHandler(this);
  }
  public long getServiceId() {
    return 3344047614L;
  }
}
