/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.gate.hotgen;

import ir.ntnaeem.hottentot.runtime.Argument;
import ir.ntnaeem.hottentot.runtime.Request;
import ir.ntnaeem.hottentot.runtime.RequestHandler;
import ir.ntnaeem.hottentot.runtime.Response;
import ir.ntnaeem.hottentot.runtime.Service;
import ir.ntnaeem.hottentot.runtime.exception.MethodNotSupportException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientConnectException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientReadException;
import ir.ntnaeem.hottentot.runtime.exception.TcpClientWriteException;
import ir.ntnaeem.hottentot.serializerHelper.PDTDeserializer;
import ir.ntnaeem.hottentot.serializerHelper.PDTSerializer;
import java.util.List;

public class GateRequestHandler extends RequestHandler {
  public GateRequestHandler(Service service) {
    super(service);
  }
  @Override
  public Response handleRequest(Request request) throws TcpClientWriteException, TcpClientReadException, TcpClientConnectException, MethodNotSupportException {
    long methodId = request.getMethodId();
    GateService gateImpl = (AbstractGateService) service;

    if(methodId == 1548427490L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedMessage = arg0.getData();
      Message message = new Message();
      message.deserialize(serializedMessage);
      Response response = new Response();
      long result = gateImpl.enqueue(message);
      byte[] serializedResult = PDTSerializer.getUint64( result );
      response.setStatusCode((byte) 0);
      response.setData(serializedResult);
      response.setLength(serializedResult.length + 1);
      return response;
    }
    if(methodId == 118643832L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedId = arg0.getData();
      long id = PDTDeserializer.getUint64(serializedId);
      Response response = new Response();
      short result = gateImpl.getStatus(id);
      byte[] serializedResult = PDTSerializer.getUint16( result );
      response.setStatusCode((byte) 0);
      response.setData(serializedResult);
      response.setLength(serializedResult.length + 1);
      return response;
    }
    if(methodId == 3250188767L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedId = arg0.getData();
      long id = PDTDeserializer.getUint64(serializedId);
      Response response = new Response();
      gateImpl.discard(id);
      response.setStatusCode((byte) 0);
      response.setData(new byte[]{0});
      response.setLength(0);
      return response;
    }
    if(methodId == 2484924834L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedLabel = arg0.getData();
      String label = PDTDeserializer.getString(serializedLabel);
      Response response = new Response();
      boolean result = gateImpl.hasMore(label);
      byte[] serializedResult = PDTSerializer.getBool( result );
      response.setStatusCode((byte) 0);
      response.setData(serializedResult);
      response.setLength(serializedResult.length + 1);
      return response;
    }
    if(methodId == 3070562612L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedLabel = arg0.getData();
      String label = PDTDeserializer.getString(serializedLabel);
      Message message = null;
      Response response = new Response();
      message = gateImpl.popNext(label);
      byte[] serializedMessage;
      if(message == null){
        serializedMessage  = new byte[0];
      }else{
      serializedMessage = message.serialize();
      }
      response.setStatusCode((byte) 0);
      response.setData(serializedMessage);
      response.setLength(serializedMessage.length + 1);
      return response;
    }
    if(methodId == 3312297367L){
      List <Argument> args = request.getArgs();
      Argument arg0 = args.get(0);
      byte[] serializedId = arg0.getData();
      long id = PDTDeserializer.getUint64(serializedId);
      Response response = new Response();
      gateImpl.ack(id);
      response.setStatusCode((byte) 0);
      response.setData(new byte[]{0});
      response.setLength(0);
      return response;
    }

    throw new MethodNotSupportException("method id is incorrect");
  }
}
