/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package ir.ntnaeem.gate.hotgen;

import ir.ntnaeem.hottentot.runtime.Service;
import java.util.List;

public interface GateTestService extends Service {
  long enqueueAsIncomingMessage(Message message);

}
