/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.gate.hotgen;

public class GateTestServiceProxyBuilder {

  public static GateTestService create(String host, int port) {
    return new GateTestServiceProxy(host,port);
  }

  public static void destroy() {
    //TODO
  }
}
