/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package ir.ntnaeem.gate.hotgen;

import ir.ntnaeem.hottentot.runtime.Service;
import java.util.List;

public interface GateService extends Service {
  long enqueue(Message message);
  short getStatus(long id);
  void discard(long id);
  boolean hasMore(String label);
  Message popNext(String label);
  void ack(long id);

}
