/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 07-05-2016 11:20:04
 * Name: transport_monitor_service_impl.cc
 * Description:
 *   This file contains empty implementation of sample stub.
 ******************************************************************/
 
#include <org/labcrypto/hottentot/runtime/configuration.h>
#include <org/labcrypto/hottentot/runtime/logger.h>
#include <org/labcrypto/hottentot/runtime/utils.h>

#include "transport_monitor_service_impl.h"

#include "../enqueue_report.h"
#include "../transport_message.h"


namespace org {
namespace labcrypto {
namespace fence {
namespace transport {
  void
  TransportMonitorServiceImpl::OnInit() {
    // TODO: Called when service is initializing.
  }
  void
  TransportMonitorServiceImpl::OnShutdown() {
    // TODO: Called when service is shutting down.
  }
  void
  TransportMonitorServiceImpl::GetCurrentStat(
    ::org::labcrypto::hottentot::Utf8String &out, 
    ::org::labcrypto::hottentot::runtime::service::HotContext &hotContext
  ) {
    if (::org::labcrypto::hottentot::runtime::Configuration::Verbose()) {
      ::org::labcrypto::hottentot::runtime::Logger::GetOut() << 
        "[" << ::org::labcrypto::hottentot::runtime::Utils::GetCurrentUTCTimeString() << "]: " <<
          "TransportMonitorServiceImpl::GetCurrentStat() is called." << std::endl;
    }
    // TODO
  }
} // END OF NAMESPACE transport
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org