/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 29-02-2016 01:23:46
 * Name: enums.h
 * Description:
 *   This file contains all enumerations from all modules.
 ******************************************************************/

#ifndef _IR_NTNAEEM_GATE_TRANSPORT__ENUMS_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__ENUMS_H_

namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif