/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 07-05-2016 11:07:50
 * Name: enums.h
 * Description:
 *   This file contains all enumerations from all modules.
 ******************************************************************/

#ifndef _ORG_LABCRYPTO_FENCE_TRANSPORT__ENUMS_H_
#define _ORG_LABCRYPTO_FENCE_TRANSPORT__ENUMS_H_

namespace org {
namespace labcrypto {
namespace fence {
namespace transport {
  enum TransportMessageStatus {
    kTransportMessageStatus___Unknown = 0,
    kTransportMessageStatus___Arrived = 200,
    kTransportMessageStatus___ReadyForPop = 201,
    kTransportMessageStatus___PoppedButNotAcked = 202,
    kTransportMessageStatus___PoppedAndAcked = 203,
    kTransportMessageStatus___EnqueuedForTransmission = 204,
    kTransportMessageStatus___EnqueueFailed = 205,
    kTransportMessageStatus___ReadyForRetrieval = 206,
    kTransportMessageStatus___RetrievedButNotAcked = 207,
    kTransportMessageStatus___RetrievedAndAcked = 208
  };
} // END OF NAMESPACE transport
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org

#endif