/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 02-04-2016 12:37:55
 * Name: enums.h
 * Description:
 *   This file contains all enumerations from all modules.
 ******************************************************************/

#ifndef _IR_NTNAEEM_GATE_TRANSPORT__ENUMS_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__ENUMS_H_

namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  enum TransportMessageStatus {
    kTransportMessageStatus___Unknown = 0,
    kTransportMessageStatus___Arrived = 200,
    kTransportMessageStatus___ReadyForPop = 201,
    kTransportMessageStatus___PoppedButNotAcked = 202,
    kTransportMessageStatus___PoppedAndAcked = 203,
    kTransportMessageStatus___EnqueuedForTransmission = 204,
    kTransportMessageStatus___ReadyForRetrieval = 205,
    kTransportMessageStatus___RetrievedButNotAcked = 206,
    kTransportMessageStatus___RetrievedAndAcked = 207
  };
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif