/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 07-05-2016 11:07:50
 * Name: transport_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <org/labcrypto/hottentot/runtime/request.h>
#include <org/labcrypto/hottentot/runtime/response.h>

#include "transport_service_request_handler.h"
#include "abstract_transport_service.h"
#include "transport_service.h"
#include "../enqueue_report.h"
#include "../transport_message.h"


namespace org {
namespace labcrypto {
namespace fence {
namespace transport {
namespace service {
  void 
  TransportServiceRequestHandler::HandleRequest(::org::labcrypto::hottentot::runtime::Request &request, ::org::labcrypto::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 3587101452) {
      ::org::labcrypto::fence::transport::service::AbstractTransportService *serviceObject = 
        dynamic_cast< ::org::labcrypto::fence::transport::service::AbstractTransportService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::org::labcrypto::hottentot::List< ::org::labcrypto::fence::transport::TransportMessage> messages;
      messages.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::org::labcrypto::hottentot::runtime::service::HotContext hotContext;
      
      ::org::labcrypto::hottentot::List< ::org::labcrypto::fence::transport::EnqueueReport> result;
      try {
        serviceObject->Transmit(messages, result, hotContext);      messages.Purge();

      } catch (std::exception &e) {
        hotContext.SetFaultyResponse(e.what(), 50);
      } catch (...) {
        hotContext.SetFaultyResponse("Unknown server side exception.", 51);
      }
      /*
       * Serializiation of returned object
       */
      unsigned char *serializedData = 0;
      uint32_t serializedDataLength = 0;
      if (hotContext.GetResponseStatusCode() == 0) {
        serializedData = result.Serialize(&serializedDataLength);
      result.Purge();
      } else {
        ::org::labcrypto::hottentot::Utf8String faultMessage(hotContext.GetFaultMessage());
        serializedData = faultMessage.Serialize(&serializedDataLength);
      }
      response.SetStatusCode(hotContext.GetResponseStatusCode());
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 2373442179) {
      ::org::labcrypto::fence::transport::service::AbstractTransportService *serviceObject = 
        dynamic_cast< ::org::labcrypto::fence::transport::service::AbstractTransportService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::org::labcrypto::hottentot::UInt32 slaveId;
      slaveId.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::org::labcrypto::hottentot::runtime::service::HotContext hotContext;
      
      ::org::labcrypto::hottentot::List< ::org::labcrypto::fence::transport::TransportMessage> result;
      try {
        serviceObject->Retrieve(slaveId, result, hotContext);
      } catch (std::exception &e) {
        hotContext.SetFaultyResponse(e.what(), 50);
      } catch (...) {
        hotContext.SetFaultyResponse("Unknown server side exception.", 51);
      }
      /*
       * Serializiation of returned object
       */
      unsigned char *serializedData = 0;
      uint32_t serializedDataLength = 0;
      if (hotContext.GetResponseStatusCode() == 0) {
        serializedData = result.Serialize(&serializedDataLength);
      result.Purge();
      } else {
        ::org::labcrypto::hottentot::Utf8String faultMessage(hotContext.GetFaultMessage());
        serializedData = faultMessage.Serialize(&serializedDataLength);
      }
      response.SetStatusCode(hotContext.GetResponseStatusCode());
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 1694709958) {
      ::org::labcrypto::fence::transport::service::AbstractTransportService *serviceObject = 
        dynamic_cast< ::org::labcrypto::fence::transport::service::AbstractTransportService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::org::labcrypto::hottentot::List< ::org::labcrypto::hottentot::UInt64> masterMIds;
      masterMIds.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::org::labcrypto::hottentot::runtime::service::HotContext hotContext;
      
      try {
        serviceObject->Ack(masterMIds, hotContext);      masterMIds.Purge();

      } catch (std::exception &e) {
        hotContext.SetFaultyResponse(e.what(), 50);
      } catch (...) {
        hotContext.SetFaultyResponse("Unknown server side exception.", 51);
      }
      /*
       * Serializiation of returned object
       */
      unsigned char *serializedData = 0;
      uint32_t serializedDataLength = 0;
      if (hotContext.GetResponseStatusCode() == 0) {
        serializedData = 0;
      } else {
        ::org::labcrypto::hottentot::Utf8String faultMessage(hotContext.GetFaultMessage());
        serializedData = faultMessage.Serialize(&serializedDataLength);
      }
      response.SetStatusCode(hotContext.GetResponseStatusCode());
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 1154637673) {
      ::org::labcrypto::fence::transport::service::AbstractTransportService *serviceObject = 
        dynamic_cast< ::org::labcrypto::fence::transport::service::AbstractTransportService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::org::labcrypto::hottentot::UInt64 masterMId;
      masterMId.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::org::labcrypto::hottentot::runtime::service::HotContext hotContext;
      
      ::org::labcrypto::hottentot::UInt16 result;
      try {
        serviceObject->GetStatus(masterMId, result, hotContext);
      } catch (std::exception &e) {
        hotContext.SetFaultyResponse(e.what(), 50);
      } catch (...) {
        hotContext.SetFaultyResponse("Unknown server side exception.", 51);
      }
      /*
       * Serializiation of returned object
       */
      unsigned char *serializedData = 0;
      uint32_t serializedDataLength = 0;
      if (hotContext.GetResponseStatusCode() == 0) {
        serializedData = result.Serialize(&serializedDataLength);
      } else {
        ::org::labcrypto::hottentot::Utf8String faultMessage(hotContext.GetFaultMessage());
        serializedData = faultMessage.Serialize(&serializedDataLength);
      }
      response.SetStatusCode(hotContext.GetResponseStatusCode());
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE transport
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org