/***********************************************************************
 * Generated by Hottentot CC Generator
 * Date: 05-05-2016 01:33:01
 * Name: gate_monitor_service_request_handler.h
 * Description:
 *   This file contains definition of service's request handler class.
 ***********************************************************************/

#ifndef _ORG_LABCRYPTO_FENCE__SERVICE__GATE_MONITOR_SERVICE_REQUEST_HANDLER_H_
#define _ORG_LABCRYPTO_FENCE__SERVICE__GATE_MONITOR_SERVICE_REQUEST_HANDLER_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <org/labcrypto/hottentot/runtime/service/request_handler.h>


namespace org {
namespace labcrypto {
namespace fence {
namespace service {
  class GateMonitorServiceRequestHandler : public ::org::labcrypto::hottentot::runtime::service::RequestHandler {
  public:
    GateMonitorServiceRequestHandler(::org::labcrypto::hottentot::runtime::service::Service *service)
      : ::org::labcrypto::hottentot::runtime::service::RequestHandler(service) {
    }
    virtual ~GateMonitorServiceRequestHandler() {}
  public:
    virtual void HandleRequest(::org::labcrypto::hottentot::runtime::Request &request,
                                                   ::org::labcrypto::hottentot::runtime::Response &response);
  };
} // END OF NAMESPACE service
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org

#endif