/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 05-05-2016 01:33:01
 * Name: gate_test_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "gate_test_service_proxy_builder.h"
#include "gate_test_service_proxy.h"


namespace org {
namespace labcrypto {
namespace fence {
namespace proxy {
  GateTestService*
  GateTestServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new GateTestServiceProxy(host, port);
  }
  void
  GateTestServiceProxyBuilder::Destroy(GateTestService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org