/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.gate.hotgen.server;

import ir.ntnaeem.hottentot.runtime.Service;
import ir.ntnaeem.hottentot.runtime.ServiceRuntime;
import java.io.IOException;

public class Main {
  public static void main(String[] args) throws IOException {
    ir.ntnaeem.hottentot.runtime.config.Config.setMainArgs(args);
    ir.ntnaeem.hottentot.runtime.config.Config.setConfigPropertiesFromConfigFile();
    ServiceRuntime serviceRuntime = new ServiceRuntime();
    Service gateService = new GateImpl();
    serviceRuntime.register("127.0.0.1",8080, gateService);
    Service gatemonitorService = new GateMonitorImpl();
    serviceRuntime.register("127.0.0.1",8080, gatemonitorService);
    Service gatetestService = new GateTestImpl();
    serviceRuntime.register("127.0.0.1",8080, gatetestService);

    serviceRuntime.start();
  }
}



