/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 07-05-2016 11:20:04
 * Name: transport_monitor_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "transport_monitor_service_proxy_builder.h"
#include "transport_monitor_service_proxy.h"


namespace org {
namespace labcrypto {
namespace fence {
namespace transport {
namespace proxy {
  TransportMonitorService*
  TransportMonitorServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new TransportMonitorServiceProxy(host, port);
  }
  void
  TransportMonitorServiceProxyBuilder::Destroy(TransportMonitorService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE transport
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org