/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 29-03-2016 10:58:47
 * Name: transport_monitor_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "transport_monitor_service_proxy_builder.h"
#include "transport_monitor_service_proxy.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
namespace proxy {
  TransportMonitorService*
  TransportMonitorServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new TransportMonitorServiceProxy(host, port);
  }
  void
  TransportMonitorServiceProxyBuilder::Destroy(TransportMonitorService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir