/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import org.labcrypto.hottentot.runtime.RequestHandler;


public abstract class AbstractGateService implements GateService {	
  public RequestHandler makeRequestHandler() {
    return new GateRequestHandler(this);
  }
  public long getServiceId() {
    return 2590780894L;
  }
}
