/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import java.util.*;

import org.labcrypto.hottentot.runtime.Argument;
import org.labcrypto.hottentot.runtime.Proxy;
import org.labcrypto.hottentot.runtime.Request;
import org.labcrypto.hottentot.runtime.Response;
import org.labcrypto.hottentot.runtime.TcpClient;
import org.labcrypto.hottentot.runtime.exception.HottentotRuntimeException;
import org.labcrypto.hottentot.runtime.exception.TcpClientConnectException;
import org.labcrypto.hottentot.runtime.exception.TcpClientReadException;
import org.labcrypto.hottentot.runtime.exception.TcpClientWriteException;
import org.labcrypto.hottentot.runtime.exception.TcpClientCloseException;
import org.labcrypto.hottentot.runtime.factory.ProtocolFactory;
import org.labcrypto.hottentot.runtime.factory.TcpClientFactory;
import org.labcrypto.hottentot.runtime.protocol.Protocol;


public class GateTestServiceProxy extends AbstractGateTestService implements Proxy {
	
  private String host;
  private int port;

  public GateTestServiceProxy(String host, int port) {
    this.host = host;
    this.port = port;
  }
  public long enqueueAsIncomingMessage(Message message) { 
    //serialize message
    byte[] serializedMessage = message.serialize();

    //make request
    Request request = new Request();
    request.setServiceId(1988326604L);
    request.setMethodId(1300055394L);
    request.setArgumentCount((byte) 1);
    request.setType(Request.RequestType.InvokeStateless);
    Argument arg0 = new Argument();
    arg0.setDataLength(serializedMessage.length);
    arg0.setData(serializedMessage);
    request.addArgument(arg0);
    int dataLength = 0;
    //calculate data length for every argument
    // calulate messageDataLength
    int messageDataLength= serializedMessage.length;
    int messageDataLengthByteArrayLength = 1;
    if (messageDataLength >= 0x80) {
      if (messageDataLength <= 0xff) {
        //ex 0x81 0xff
        messageDataLengthByteArrayLength = 2;
      } else if (messageDataLength <= 0xffff) {
        //ex 0x82 0xff 0xff
        messageDataLengthByteArrayLength = 3;
      } else if (messageDataLength <= 0xffffff) {
        //ex 0x83 0xff 0xff 0xff
        messageDataLengthByteArrayLength = 4;
      }
    }
    dataLength += messageDataLength + messageDataLengthByteArrayLength;
    // arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    // connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    // serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    // send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    // read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    // close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize uint64part from response
    if (response.getStatusCode() == -1) {
      //TODO
    }
    _Int64 ret = new _Int64();
    ret.deserialize(response.getData());
    return ret.getValue();
  }

  public void destroy() {
    //TODO
  }
}
