/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package org.labcrypto.fence;

import java.util.*;

import org.labcrypto.hottentot.runtime.Service;


public interface GateTestService extends Service {
  long enqueueAsIncomingMessage(Message message);

}
