/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import java.io.IOException;

import org.labcrypto.fence.GateService;
import org.labcrypto.fence.GateServiceProxyBuilder;
import org.labcrypto.fence.GateMonitorService;
import org.labcrypto.fence.GateMonitorServiceProxyBuilder;
import org.labcrypto.fence.GateTestService;
import org.labcrypto.fence.GateTestServiceProxyBuilder;



public class SampleClient {
  public static void main(String[] args) throws IOException {
    org.labcrypto.hottentot.runtime.config.Config.setMainArgs(args);
    final GateService gateProxy = GateServiceProxyBuilder.create("127.0.0.1", 8080);
    final GateMonitorService gatemonitorProxy = GateMonitorServiceProxyBuilder.create("127.0.0.1", 8080);
    final GateTestService gatetestProxy = GateTestServiceProxyBuilder.create("127.0.0.1", 8080);

    //use server methods on proxies
  }
}