/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import java.io.IOException;

import org.labcrypto.fence.FenceService;
import org.labcrypto.fence.FenceServiceProxyBuilder;
import org.labcrypto.fence.FenceMonitorService;
import org.labcrypto.fence.FenceMonitorServiceProxyBuilder;
import org.labcrypto.fence.FenceTestService;
import org.labcrypto.fence.FenceTestServiceProxyBuilder;



public class SampleClient {
  public static void main(String[] args) throws IOException {
    org.labcrypto.hottentot.runtime.config.Config.setMainArgs(args);
    final FenceService fenceProxy = FenceServiceProxyBuilder.create("127.0.0.1", 8080);
    final FenceMonitorService fencemonitorProxy = FenceMonitorServiceProxyBuilder.create("127.0.0.1", 8080);
    final FenceTestService fencetestProxy = FenceTestServiceProxyBuilder.create("127.0.0.1", 8080);

    //use server methods on proxies
  }
}