/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 05-05-2016 01:33:01
 * Name: enums.h
 * Description:
 *   This file contains all enumerations from all modules.
 ******************************************************************/

#ifndef _ORG_LABCRYPTO_FENCE__ENUMS_H_
#define _ORG_LABCRYPTO_FENCE__ENUMS_H_

namespace org {
namespace labcrypto {
namespace fence {
  enum MessageStatus {
    kMessageStatus___Unknown = 0,
    kMessageStatus___EnqueuedForTransmission = 100,
    kMessageStatus___Transmitted = 101,
    kMessageStatus___TransmissionFailed = 102,
    kMessageStatus___ReadyForPop = 103,
    kMessageStatus___PoppedButNotAcked = 104,
    kMessageStatus___PoppedAndAcked = 105
  };
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org

#endif