/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import org.labcrypto.hottentot.runtime.RequestHandler;


public abstract class AbstractGateTestService implements GateTestService {	
  public RequestHandler makeRequestHandler() {
    return new GateTestRequestHandler(this);
  }
  public long getServiceId() {
    return 1988326604L;
  }
}
