/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import org.labcrypto.hottentot.runtime.RequestHandler;


public abstract class AbstractFenceTestService implements FenceTestService {	
  public RequestHandler makeRequestHandler() {
    return new FenceTestRequestHandler(this);
  }
  public long getServiceId() {
    return 908149993L;
  }
}
