/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import org.labcrypto.hottentot.runtime.RequestHandler;


public abstract class AbstractGateMonitorService implements GateMonitorService {	
  public RequestHandler makeRequestHandler() {
    return new GateMonitorRequestHandler(this);
  }
  public long getServiceId() {
    return 3779953030L;
  }
}
