/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import org.labcrypto.hottentot.runtime.RequestHandler;


public abstract class AbstractFenceService implements FenceService {	
  public RequestHandler makeRequestHandler() {
    return new FenceRequestHandler(this);
  }
  public long getServiceId() {
    return 3025599164L;
  }
}
