/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

public class FenceMonitorServiceProxyBuilder {

  public static FenceMonitorService create(String host, int port) {
    return new FenceMonitorServiceProxy(host,port);
  }

  public static void destroy() {
    //TODO
  }
}
