/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

import java.util.*;

import org.labcrypto.hottentot.*;
import org.labcrypto.hottentot.runtime.Argument;
import org.labcrypto.hottentot.runtime.Proxy;
import org.labcrypto.hottentot.runtime.Request;
import org.labcrypto.hottentot.runtime.Response;
import org.labcrypto.hottentot.runtime.TcpClient;
import org.labcrypto.hottentot.runtime.exception.HottentotRuntimeException;
import org.labcrypto.hottentot.runtime.exception.TcpClientConnectException;
import org.labcrypto.hottentot.runtime.exception.TcpClientReadException;
import org.labcrypto.hottentot.runtime.exception.TcpClientWriteException;
import org.labcrypto.hottentot.runtime.exception.TcpClientCloseException;
import org.labcrypto.hottentot.runtime.factory.ProtocolFactory;
import org.labcrypto.hottentot.runtime.factory.TcpClientFactory;
import org.labcrypto.hottentot.runtime.protocol.Protocol;


public class FenceMonitorServiceProxy extends AbstractFenceMonitorService implements Proxy {
	
  private String host;
  private int port;

  public FenceMonitorServiceProxy(String host, int port) {
    this.host = host;
    this.port = port;
  }
  public String getCurrentStat() { 

    //make request
    Request request = new Request();
    request.setServiceId(375409744L);
    request.setMethodId(3234349133L);
    request.setArgumentCount((byte) 0);
    request.setType(Request.RequestType.InvokeStateless);
    int dataLength = 0;
    //calculate data length for every argument
    // arg count(1) + request type(1) + method ID(4) + service ID(4) = 10;
    request.setLength(10 + dataLength);
    // connect to server
    TcpClient tcpClient = TcpClientFactory.create();
    try{
      tcpClient.connect(host, port);
    } catch (TcpClientConnectException e) {
      throw new HottentotRuntimeException(e);
    }
    // serialize request according to HTNP
    Protocol protocol = ProtocolFactory.create();
    byte[] serializedRequest = protocol.serializeRequest(request);
    // send request
    try {
      tcpClient.write(serializedRequest);
    } catch (TcpClientWriteException e) {
      throw new HottentotRuntimeException(e);
    }
    // read response from server
    byte[] buffer = new byte[256];
    while (!protocol.isResponseComplete()) {
      byte[] dataChunkRead;
      try {
        dataChunkRead = tcpClient.read();
      } catch (TcpClientReadException e) {
        throw new HottentotRuntimeException(e);
      }
      protocol.processDataForResponse(dataChunkRead);
    }
    Response response = protocol.getResponse();
    // close everything
     try { 
       tcpClient.close(); 
    } catch (TcpClientCloseException e) { 
      e.printStackTrace(); 
    } 
    //deserialize stringpart from response
    if (response.getStatusCode() == -1) {
      //TODO
    }
    _String ret = new _String();
    ret.deserialize(response.getData());
    return ret.getValue();
  }

  public void destroy() {
    //TODO
  }
}
