/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package org.labcrypto.fence;

import java.util.*;

import org.labcrypto.hottentot.runtime.Service;


public interface FenceMonitorService extends Service {
  String getCurrentStat();

}
