/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/

package org.labcrypto.fence;

import java.util.*;

import org.labcrypto.hottentot.runtime.Service;


public interface FenceService extends Service {
  long enqueue(Message message);
  short getStatus(long id);
  void discard(long id);
  boolean hasMore(String label);
  Message popNext(String label);
  void ack(long id);

}
