/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package org.labcrypto.fence;

public class GateServiceProxyBuilder {

  public static GateService create(String host, int port) {
    return new GateServiceProxy(host,port);
  }

  public static void destroy() {
    //TODO
  }
}
