/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 07-05-2016 11:07:50
 * Name: gate_monitor_service_proxy_builder.cc
 * Description:
 *   This file contains implementation of the proxy builder class.
 ******************************************************************/

#include "gate_monitor_service_proxy_builder.h"
#include "gate_monitor_service_proxy.h"


namespace org {
namespace labcrypto {
namespace fence {
namespace proxy {
  GateMonitorService*
  GateMonitorServiceProxyBuilder::Create(std::string host, uint32_t port) {
    return new GateMonitorServiceProxy(host, port);
  }
  void
  GateMonitorServiceProxyBuilder::Destroy(GateMonitorService *service) {
    delete service;
  }
} // END OF NAMESPACE proxy
} // END OF NAMESPACE fence
} // END OF NAMESPACE labcrypto
} // END OF NAMESPACE org