/******************************************************************
 * Generated by Hottentot JAVA Generator
 * Date: 
 * Name: 
 * Description:
 *   
 ******************************************************************/
package ir.ntnaeem.gate.hotgen.client;

import ir.ntnaeem.gate.hotgen.GateService;
import ir.ntnaeem.gate.hotgen.GateServiceProxyBuilder;
import ir.ntnaeem.gate.hotgen.GateMonitorService;
import ir.ntnaeem.gate.hotgen.GateMonitorServiceProxyBuilder;
import ir.ntnaeem.gate.hotgen.GateTestService;
import ir.ntnaeem.gate.hotgen.GateTestServiceProxyBuilder;

import java.io.IOException;

public class Main {
  public static void main(String[] args) throws IOException {
    ir.ntnaeem.hottentot.runtime.config.Config.setMainArgs(args);
    final GateService gateProxy = GateServiceProxyBuilder.create("127.0.0.1", 8080);
    final GateMonitorService gatemonitorProxy = GateMonitorServiceProxyBuilder.create("127.0.0.1", 8080);
    final GateTestService gatetestProxy = GateTestServiceProxyBuilder.create("127.0.0.1", 8080);

    //use server methods on proxies
  }
}